services:
  streamrecorder:
    build: .
    container_name: streamrecorder

    ports:
    - 8080:8080

    volumes:
    - ./records:/records

    environment:
      - PORT=8080
      - DIR=/records
      #- SCHEDULE=true
      #- RETENTION_DAYS=30
      #- NEWS_API=https://news.radio-t.com/api/v1
