// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package chapters

import (
	"context"
	"sync"
	"time"
)

// Ensure, that NewsProviderMock does implement NewsProvider.
// If this is not the case, regenerate this file with moq.
var _ NewsProvider = &NewsProviderMock{}

// NewsProviderMock is a mock implementation of NewsProvider.
//
//	func TestSomethingThatUsesNewsProvider(t *testing.T) {
//
//		// make and configure a mocked NewsProvider
//		mockedNewsProvider := &NewsProviderMock{
//			FetchActiveIDFunc: func(ctx context.Context) (string, error) {
//				panic("mock out the FetchActiveID method")
//			},
//			FetchArticleFunc: func(ctx context.Context, id string) (Article, error) {
//				panic("mock out the FetchArticle method")
//			},
//			WaitActiveChangeFunc: func(ctx context.Context, timeout time.Duration) (string, error) {
//				panic("mock out the WaitActiveChange method")
//			},
//		}
//
//		// use mockedNewsProvider in code that requires NewsProvider
//		// and then make assertions.
//
//	}
type NewsProviderMock struct {
	// FetchActiveIDFunc mocks the FetchActiveID method.
	FetchActiveIDFunc func(ctx context.Context) (string, error)

	// FetchArticleFunc mocks the FetchArticle method.
	FetchArticleFunc func(ctx context.Context, id string) (Article, error)

	// WaitActiveChangeFunc mocks the WaitActiveChange method.
	WaitActiveChangeFunc func(ctx context.Context, timeout time.Duration) (string, error)

	// calls tracks calls to the methods.
	calls struct {
		// FetchActiveID holds details about calls to the FetchActiveID method.
		FetchActiveID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// FetchArticle holds details about calls to the FetchArticle method.
		FetchArticle []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
		}
		// WaitActiveChange holds details about calls to the WaitActiveChange method.
		WaitActiveChange []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Timeout is the timeout argument value.
			Timeout time.Duration
		}
	}
	lockFetchActiveID    sync.RWMutex
	lockFetchArticle     sync.RWMutex
	lockWaitActiveChange sync.RWMutex
}

// FetchActiveID calls FetchActiveIDFunc.
func (mock *NewsProviderMock) FetchActiveID(ctx context.Context) (string, error) {
	if mock.FetchActiveIDFunc == nil {
		panic("NewsProviderMock.FetchActiveIDFunc: method is nil but NewsProvider.FetchActiveID was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockFetchActiveID.Lock()
	mock.calls.FetchActiveID = append(mock.calls.FetchActiveID, callInfo)
	mock.lockFetchActiveID.Unlock()
	return mock.FetchActiveIDFunc(ctx)
}

// FetchActiveIDCalls gets all the calls that were made to FetchActiveID.
// Check the length with:
//
//	len(mockedNewsProvider.FetchActiveIDCalls())
func (mock *NewsProviderMock) FetchActiveIDCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockFetchActiveID.RLock()
	calls = mock.calls.FetchActiveID
	mock.lockFetchActiveID.RUnlock()
	return calls
}

// FetchArticle calls FetchArticleFunc.
func (mock *NewsProviderMock) FetchArticle(ctx context.Context, id string) (Article, error) {
	if mock.FetchArticleFunc == nil {
		panic("NewsProviderMock.FetchArticleFunc: method is nil but NewsProvider.FetchArticle was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  string
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockFetchArticle.Lock()
	mock.calls.FetchArticle = append(mock.calls.FetchArticle, callInfo)
	mock.lockFetchArticle.Unlock()
	return mock.FetchArticleFunc(ctx, id)
}

// FetchArticleCalls gets all the calls that were made to FetchArticle.
// Check the length with:
//
//	len(mockedNewsProvider.FetchArticleCalls())
func (mock *NewsProviderMock) FetchArticleCalls() []struct {
	Ctx context.Context
	ID  string
} {
	var calls []struct {
		Ctx context.Context
		ID  string
	}
	mock.lockFetchArticle.RLock()
	calls = mock.calls.FetchArticle
	mock.lockFetchArticle.RUnlock()
	return calls
}

// WaitActiveChange calls WaitActiveChangeFunc.
func (mock *NewsProviderMock) WaitActiveChange(ctx context.Context, timeout time.Duration) (string, error) {
	if mock.WaitActiveChangeFunc == nil {
		panic("NewsProviderMock.WaitActiveChangeFunc: method is nil but NewsProvider.WaitActiveChange was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Timeout time.Duration
	}{
		Ctx:     ctx,
		Timeout: timeout,
	}
	mock.lockWaitActiveChange.Lock()
	mock.calls.WaitActiveChange = append(mock.calls.WaitActiveChange, callInfo)
	mock.lockWaitActiveChange.Unlock()
	return mock.WaitActiveChangeFunc(ctx, timeout)
}

// WaitActiveChangeCalls gets all the calls that were made to WaitActiveChange.
// Check the length with:
//
//	len(mockedNewsProvider.WaitActiveChangeCalls())
func (mock *NewsProviderMock) WaitActiveChangeCalls() []struct {
	Ctx     context.Context
	Timeout time.Duration
} {
	var calls []struct {
		Ctx     context.Context
		Timeout time.Duration
	}
	mock.lockWaitActiveChange.RLock()
	calls = mock.calls.WaitActiveChange
	mock.lockWaitActiveChange.RUnlock()
	return calls
}
